<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update video gallery' => 'تحديث ألبوم الفيديو',
    'Video url' => 'رابط الفيديو',
    'Be careful in Code field. Pay attention to field hint.' => 'يجب أن تنتبه لهذا الحقل.',
    'Code' => 'الكود',
    'Create video' => 'اضافة فيديو',
    'Create video gallery' => 'اضافة ألبوم الفيديو ',
    'Created at' => 'انشأ بتاريخ',
    'Created at {0, date, MMMM dd, YYYY HH:mm}' => 'اضافة بتاريخ: {0, date, dd MMMM YYYY, HH:mm}',
    'Description' => 'نص التعليق',
    'Don\'t change this value, if you not sure for what it is for.' => 'لا غير هذه القيمة اذا لم تكون تعرف ماذا تعني.',
    'Edit' => 'تحرير',
    'Galleries' => 'الألبومات',
    'Information' => 'المعلومات',
    'Manage video galleries' => 'ادارة ألبومات الفيديو',
    'Manage videos' => 'ادارة الفيديوهات',
    'Name' => 'اللأسم',
    'Only latin characters, numbers and symbols (.-_) allowed. Spaces not allowed.' => 'فقط الحروف الاتينية والرمز الآتي(.-_). المسافات غير مقبولة.',
    'Save' => 'حفظ',
    'Sort index' => 'الترتيب',
    'There is no video gallery with code "{code}"' => 'لا يوجد فيديو يحمل الكود "{code}"',
    'Title' => 'العنوان',
    'Update video' => 'تحديث الفيديو',
    'Updated at' => 'تاريخ آخر تعديل',
    'Video gallery' => 'ألبوم الفيديو',
    'Video gallery has been created' => 'تم انشاء ألبوم فيديوهات جديد',
    'Video gallery has been deleted' => 'تم حذف ألبوم فيديوهات',
    'Video gallery has been updated' => 'تم تحديث ألبوم فيديوهات',
    'Video has been created' => 'تم اضافة فيديو جديد',
    'Video has been deleted' => 'تم خذف فيديو',
    'Video has been updated' => 'تم تحديث الفيديو',
    'Videos' => 'الفيديوهات',
    '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, dd MMMM YYYY, HH:mm}',
];
